[firebase]
type = "service_account"
project_id = "agendaatelie-18e13"
private_key_id = "6c69b3a451878adef05bfda2589e0de5084ba5a9"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCXNtOeJBhp1+ex
4dorg8A3c2Y9jTTGkYxTrhF2cT6GqXvH5bT4Dc1hNe+wYV8Xy7rFEAt7RjI41moj
1glW1lXv8yXvby9QJ8hEwIIUh8zPFhRZq9LvyIw0ItzHTjDddF0LEkHabLzTj4Ty
U+F/Uxedawv20WweAJVqMOrdGHJeEkNoYD3553nYREBMgplKW85xp9FRYFPQuH/e
cqCM7t1gvHdC0U3GobBQq9HAKht8MOFGqGE/Oqx4fgl11Pq5yBDRIgRiPaEbZ5WX
LBggB1aGFgwGittb4+wPid0+TrkqeZsFbsjUQx+HN/rwlYMCeU+fEs3KFFvn8fVG
YsKLQOiXAgMBAAECggEAI0ki9osbu08rfOHkJDVZXFcsa36Q6yk5oqlC3+2rFodk
IBBlO2EVJPMOHI2MQCRFUAjfdQO7YnH+UKB4i2/2m8iUeJvsYXr3C7wUXrAVxdk0
JHyo+1VECkJ8XHHNi0/FCnlXLp4jLgcWkemq/CgqoYxCPXU/En02YJJLrA4xWevz
RcDzkG9HLeBTAOk/iSdBlQ/IivmEjrN/i1srQ1sMs7Qfgf1kwNW4MhxZ4R35HLXW
726j63ptypcYknT4aIG99ds8Xc6A1ACtoRE7QlkA4J7Vb7hz4L6z+C2qY4Ppkq8t
Z1cRxs+hCa6n9ZAsHSNhenngf6VzYpOSgMTgx7i7SQKBgQDFB0KuQo94NZ3REEvB
PdJZ2KOmz+ksd/XndtUHSJWoEZCEOivpLzFwbfpBB2Mou5+ZxQnBGbOz8/JIrXOg
4LDCpQeuQ+XFy2g9P6LKO4LptS+GYWi1rC1FHwTDdY3ad+LsudsgzG8EBUczewLM
5wuB69iWloA2Dr2lYnF+8vQAZQKBgQDEeS7y15ZI0589C7LLODsiiNKoG42gTdQE
aWDKMDSUsjTigoM7RjFf8eJUBA7XY1ya/9PEp2NLQv7Eyn9EXO4mwc12yy7ACPqu
TfJj+rWvqfO6jMdswoCfBg2jB6Ospxe1d8dDSwxfP3SkxV50mXy5mR/RTFqyXGTb
F4cbxyVvSwKBgFgBYzZlAqJmCITua3f4PjHlg0uqSHOVbaAiwwqK0FYO6mc1eJGi
g8m9Re+v9gmmrKZJjY7UBSGXEByIZUJxumJmxmR/bW2I6pmZCASeyl3LkVvLvLKR
InNiZIVNx7vSmui0J32h8uBv3xrOkjSl6szwZID23nPG58ysiRd0O6rFAoGAWBcd
fbQ7pZt8ohpEp+kmWm2OReFUtrMuhGvbAcxrRuA/5e8ud70ZFjOVjqXjIZ9jPfvG
Lz39vxjisck5FqW0AZyTStf+tgtQmiZIr5sRKxnANbw5DgKHOMW2B4q9UAP7FVoG
9Z0IhwwkeFwl5ZGL4otNQMJDSAU1EyaRZVr85dECgYAu/DKfuRfxauKQPJP9NITm
sW0YeI0uf2EUEakOYOc7JNAhsXjfWyry71L+MO36/S3gX7u5WIE7iGw/hqnjghHc
74mb+P7F4hLczLSCERuFhju7n1JVT79xHUvC+59jdN8TURY+LwTtMCGvXaqPKesv
+t330cjfo/EG987fSvC5hA==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-xrdtd@agendaatelie-18e13.iam.gserviceaccount.com"
client_id = "118281544725765946918"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-xrdtd%40agendaatelie-18e13.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
